# keys named after psycopg2.connect parameters
# https://www.psycopg.org/docs/module.html#psycopg2.connect

[database]
dbname = "postgres"
user = "john doe"
password = "password"
host = "localhost"
port = 5432